[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[rpc_endpoints]
lisk_sepolia = "https://rpc.sepolia-api.lisk.com"

[etherscan]
lisk_sepolia = { key = "${J5ZGY8UVJ6T7EF7S6YKSDSYC69TCVDKKQE}" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
